name: CI

on:
  push:
    branches:
      - master
      - 'feature/**'
      - 'fix/**'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

  pull_request:
    branches:
      - master

  schedule:
    - cron: '0 11 * * *'
      #      | | | | |
      #      | | | | |____ day of the week (0 - 6 or SUN-SAT)
      #      | | | |____ month (1 - 12 or JAN-DEC)
      #      | | |____ day of the month (1 - 31)
      #      | |____ hour (0 - 23)
      #      |____ minute (0 - 59)

jobs:
  simple_build:
    # To prevent build a particular commit use
    #     git commit -m "......... [ci skip]"
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:

        include:
          - name: linux-gcc-debug
            build-type: Debug
            os: ubuntu-18.04
            ssl: mbedtls
            compiler: gcc
            arch: x64
            version: '5'

          # TODO: Enable after fix Makefile
          #
          #    /usr/bin/ld: ../lib/mbedtls/library/libmbedtls.a(aes.c.o): relocation R_X86_64_32S against `.bss'
          #                 can not be used when making a shared object; recompile with -fPIC
          #
          # - name: linux-clang-debug
          #   build-type: Debug
          #   os: ubuntu-18.04
          #   ssl: mbedtls
          #   compiler: clang
          #   version: '5.0'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 5

      - name: Setup Common Prerequisites
        run: |
          case ${{ runner.os }} in
            Linux*)
              # Add more toolchains
              echo 'debconf debconf/frontend select Noninteractive' | sudo debconf-set-selections
              sudo add-apt-repository ppa:ubuntu-toolchain-r/test --yes
              sudo apt-get update --quiet --yes 1>/dev/null

              # Install compiler
              source .github/install-compiler-linux.sh \
                "${{ matrix.compiler }}" "${{ matrix.version }}"

              # Install build deps
              sudo apt-get install --no-install-recommends -q -y \
                 cmake \
                 fuse \
                 libboost-program-options-dev \
                 libboost-system-dev \
                 libfuse-dev \
                 libpthread-stubs0-dev \
                 libudev-dev \
                 zlib1g-dev
              ;;
          esac

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
          architecture: ${{ matrix.arch }}

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Verify Toolchain Version
        run: |
          ${{ matrix.compiler }} --version
          cmake --version
          conan --version

      - name: Setting Up Build Vars
        run: echo "CONAN_USER_HOME=$(conan config home)" >> $GITHUB_ENV

      - name: Configure Conan
        run: |
          mkdir -p "${{ env.CONAN_USER_HOME }}/.conan/profiles"

          # Install conan profiles
          cp tools/conan/profiles/* "${{ env.CONAN_USER_HOME }}/.conan/profiles/"
          conan profile list

      - name: Install The Requirements Using Conan
        run: >-
          conan
          install .
          --install-folder .build
          --profile ${{ runner.os }}-${{ matrix.arch }}-${{ matrix.compiler }}-${{ matrix.version }}-${{ matrix.build-type }}
          --build missing

      - name: Configure client
        run: >-
          cmake
          -S .
          -B .build
          -DCMAKE_BUILD_TYPE=${{ matrix.build-type }}
          -DCMAKE_INSTALL_PREFIX="$(pwd)/install"

      - name: Build client
        run: cmake --build .build --config ${{ matrix.build-type }}

      - name: Install client
        run: cmake --build .build --config ${{ matrix.build-type }} --target install

      - name: Minimal Load Test
        run: install/bin/pcloudcc --help

      - name: Success Reporting
        if: success()
        run: git log --format=fuller -5
